---
- hosts: s6
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/vars/config.yml"
  tasks:
    - name: copy local uploads directory to remote
      synchronize:
        mode: push
        recursive: yes
        perms: yes
        times: yes
        src: "{{ playbook_dir }}/../../web/uploads/"
        dest: "{{ vhost_path }}/shared/web/uploads"
    - name: fix ownership in downloaded files locally
      file:
        path: "{{ vhost_path }}/shared/web"
        recurse: yes
        follow: no
        owner: www-data
        group: www-data
