imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: media.yml }
    - { resource: sonata.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
#parameters:
#    locale: es

# Symfony
framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - "bootstrap_3_layout.html.twig"
        - "SonataCoreBundle:Form:datepicker.html.twig"
    globals:
        google_analytics_enabled: "%google_analytics_enabled%"
        google_analytics_account: "%google_analytics_account%"
        main_brand_title:         "%project_web_title%"
        admin_tag_version:        "v1.0.01"

# Assetic
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    java:           "%path_java%"
    node:           "%path_node%"
    bundles:        [ AppBundle ]
    filters:
        cssrewrite: ~
        less:
            node:       "%path_node%"
            node_paths: [ "%path_node_modules%" ]
    assets:
        mycss:
            inputs:
                - "@AppBundle/Resources/public/css/frontend.less"
        myjs:
            inputs:
                - "%kernel.root_dir%/../vendor/components/jquery/jquery.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js"

# Doctrine
doctrine:
    dbal:
        driver:   "pdo_mysql"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                month: DoctrineExtensions\Query\Mysql\Month
                day: DoctrineExtensions\Query\Mysql\Day

# Stof Doctrine Extensions
stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            softdeleteable: true
            timestampable:  true
            sluggable:      true
            translatable:   false
            sortable:       false
            tree:           false

# FOS User
fos_user:
    db_driver:      orm
    firewall_name:  admin
    user_class:     AppBundle\Entity\User
    group:
        group_class:   AppBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# KNP Paginator
knp_paginator:
    page_range: 5
    default_options:
        page_name: pagina
    template:
        pagination: "::Pagination/custom_pagination.html.twig"
