services:
    app.portfolio_category_repository:
        class: AppBundle\Repository\PortfolioCategoryRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:PortfolioCategory
    app.city_repository:
        class: AppBundle\Repository\CityRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:City
    app.repositories_manager:
        class: AppBundle\Manager\RepositoriesManager
        arguments:
            - "@app.portfolio_category_repository"
            - "@app.city_repository"
